### ISSUE TITLE
When entering the username get error: "Unable to detect a Project Id in the current environment. "

### ISSUE THREAD

**Issue by g3rzi** [GoogleChromeLabs/passkeys-demo#31]
After entering a username, I am getting the following error:  
![image](https://github.com/user-attachments/assets/82bc3d22-1f3f-4182-bfef-49f57c90881f)

These are the error from server:  
```
C:\passkeys-demo>npm run dev

> passkey-demo@1.0.0 dev
> set NODE_ENV=localhost && node server.mjs

(node:74680) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Your app is listening on port 8080
Error: Unable to detect a Project Id in the current environment.
To learn more about authentication and Google APIs, visit:
https://cloud.google.com/docs/authentication/getting-started
    at GoogleAuth.findAndCacheProjectId (C:\passkeys-demo\node_modules\google-auth-library\build\src\auth\googleauth.js:170:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Firestore.initializeIfNeeded (C:\passkeys-demo\node_modules\@google-cloud\firestore\build\src\index.js:1163:35)
Caused by: Error
    at QueryUtil._getResponse (C:\passkeys-demo\node_modules\@google-cloud\firestore\build\src\reference\query-util.js:42:23)
    at Query._getResponse (C:\passkeys-demo\node_modules\@google-cloud\firestore\build\src\reference\query.js:792:32)
    at Query._get (C:\passkeys-demo\node_modules\@google-cloud\firestore\build\src\reference\query.js:785:35)
    at Query.get (C:\passkeys-demo\node_modules\@google-cloud\firestore\build\src\reference\query.js:754:39)
    at Object.findByUsername (file:///D:/Research/passkey/passkeys-demo/libs/db.mjs:61:42)
    at file:///D:/Research/passkey/passkeys-demo/libs/auth.mjs:110:30
    at Layer.handle [as handle_request] (C:\passkeys-demo\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\passkeys-demo\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\passkeys-demo\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\passkeys-demo\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by agektmr** [comment]
What happens if you rewrite `package.json`'s line 12 to be something like:

```
    "emulator": "firebase emulators:start --only firestore --project demo-passkeys --import=./.data --export-on-exit"
```

https://stackoverflow.com/questions/67781589/how-to-setup-a-firebase-demo-project

**Comment by g3rzi** [comment]
From what I see the only change the you did is to change the project name from `passkeys-demo` to `demo-passkeys`.   

I changed it to be like that (as you said):  
```
"emulator": "firebase emulators:start --only firestore --project demo-passkeys --import=./.data --export-on-exit"
```  

But I am receiving the same error.  
I remember that when I initalize the firebase I needed to use my google account and created a firebase project with my google account. Maybe this is related to the issue.

**Comment by g3rzi** [comment]
I think that problem is because I don't have collection in the Firebase store. 
I noticed that when I enter the username it goes to:  
https://github.com/GoogleChromeLabs/passkeys-demo/blob/cd60f6d40f6c0cc86b0ab5ca616da08909229a22/libs/db.mjs#L60  


But I don't have this collection.  

I created it: 
![image](https://github.com/user-attachments/assets/35eccbc3-f7e9-425e-9f23-84afc7bfae8e)


But when I checked again it still fail.

**Comment by agektmr** [comment]
Is this localhost or did you create a Google Cloud project?
The issue must be nothing to with the code. It's Google Cloud config you have.

Can you try:
```
gcloud config set project demo-passkeys
```

along with

```
"emulator": "firebase emulators:start --only firestore --project demo-passkeys --import=./.data --export-on-exit"
```

**Comment by g3rzi** [comment]
I removed the folder and clone again the repository.  
I run the `gcloud` command:  
```
PS C:\\passkeys-demo> gcloud config list
[accessibility]
screen_reader = False
[core]
disable_usage_reporting = True
project = demo-passkeys

Your active configuration is: [default]
```  

I run the emulator:  
![image](https://github.com/user-attachments/assets/3429d62a-9890-4a41-b4c6-d0a0d95ba1c8)


After that I run the `npm run dev` and type "john" and received the same error.  


I remember that in the beginning (a week ago) I tried to setup the firebase and I might configure it with my google account but now I run it from the passkey folder and it runs local because I can access it locally:  
  
![image](https://github.com/user-attachments/assets/566b482d-1be3-4d6e-a0d3-dabbb846a590)

**Comment by g3rzi** [comment]
I discovered that my `firebase` command was logged in to my google account by running `firebase projects:list` so I run `firebase logout`. I also removed the `.data` folder that is the folder of the firebase exports. I tried again, and same error :(.  
I don't understand what is the issue it has with the project ID.  
It writes that it unable to detect a project ID, which is `demo-passkeys`. I was supposed to create one? Because there is no option to create in the local firestore.

**Comment by agektmr** [comment]
Try changing libs/db.js L28 to

```
  process.env.GOOGLE_CLOUD_PROJECT = 'demo-passkeys';
```

I completely overlooked this part was hardcoded.

**Comment by g3rzi** [comment]
Thanks but, it didn't help but thanks to you I had an idea to put a breakpoint on this block:  
https://github.com/GoogleChromeLabs/passkeys-demo/blob/cd60f6d40f6c0cc86b0ab5ca616da08909229a22/libs/db.mjs#L26-L32  

I created a `launch.json` file under `.vscode`:  
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "runtimeExecutable": "npm",
        "runtimeArgs": [
          "run",
          "dev"
        ],
        "port": 9229,
        "skipFiles": ["<node_internals>/**"],
        "cwd": "${workspaceFolder}",
        "console": "integratedTerminal",
        "env": {
          "NODE_ENV": "localhost"
        }
      }
    ]
}
  ```

After debugging I found the problem, if you look closely, you will notice that there is an extra space in the string "localhost":  
![image](https://github.com/user-attachments/assets/f3e00406-e5ce-41fd-b55a-4adffc75dd0f)

It happened because in Windows, when you run the following command with `&&`:  
```json
    "dev": "set NODE_ENV=localhost && node server.mjs",
``` 

It adds extra space.  
To solve it, I needed to go to `package.json` and change the line to:  
```json
    "dev": "set NODE_ENV=localhost&& node server.mjs",
```

Now it works fine 😊
Thank you for you help, much appreciate!

**Comment by agektmr** [comment]
That's a very interesting bug... I'll fix it later.

**Comment by agektmr** [comment]
Thanks for reporting!
